library/urls.py
from django.urls import path
from . import views, crud

app_name = "library"

urlpatterns = [
    path(
        "",
         views.index_view,
         name="index"
    ),
    path(
        "genres/",
        views.genres_with_books,
        name="genres-with-books"
    ),
    path(
        "books/",
        crud.BookListView.as_view(),
        name="list"
    ),
    path(
        "detail/<int:pk>",
        crud.BookDetailView.as_view(),
        name="detail"
    ),
]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("library/", include("library.urls")),
]

library/models.py
from django.db import models


class Genre(models.Model):
    class Meta:
        verbose_name_plural = "Genres"

    name = models.CharField(max_length=64, unique=True)

    def __str__(self):
        return str(self.name)


class Book(models.Model):
    name = models.CharField(max_length=64)
    genre = models.ForeignKey(
        Genre,
        on_delete=models.PROTECT,
        related_name="books",
    )

    def __str__(self):
        return f"{self.name} ({self.genre.name})"

library/views.py
from django.http import HttpRequest
from django.shortcuts import render
from .models import Genre, Book


def index_view(request):
    books = (
        Book
        .objects.select_related("genre")
        .all()
    )
    context = {
        "books": books,
    }
    return render(
        request,
        "library/book-list.html",
        context
    )


def genres_with_books(request: HttpRequest):
    context = {
        "genres": (
            Genre
            .objects
            .prefetch_related("books")
            .all()
        )
    }
    return render(
        request,
        "library/genres-with-books.html",
        context,
    )

library/templates/library/book-detail.html
{% extends 'base.html' %}

{% block title %}
  {{object.name}}
{% endblock %}

{% block body %}
  <h1>{{object.name}}</h1>
    {{object.genre.name}}
  <div>
    <a href="{% url 'library:list' %}">Back to book list</a>
  </div>

  {% include 'common/footer-common.html' %}
{% endblock %}

library/templates/library/book-list.html
`{% extends 'base.html' %}

{% block title %}
  Books
{% endblock %}

{% block body %}
  <h1>Books:</h1>
  {% if books %}
    <ul>
      {% for book in books %}
        <li>
          <strong>
           <a href="{% url 'library:detail' pk=book.pk %}">
             {{ book.name }}
          </a>
          </strong>
          <em>({{ book.genre.name }})</em>.
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h2>No books yet!</h2>
  {% endif %}

  {% include 'common/footer-common.html' %}
{% endblock %}`

library/templates/library/genres-with-books.html
{% extends 'base.html' %}

{% block title %}
  Genres-w-books
{% endblock %}

{% block body %}
  <h1>Genres</h1>
  <h2>With books</h2>

  {% if genres %}
    <ul>
      {% for genre in genres %}
        <li>
          <strong>{{ genre }}</strong>
          <ul>
            {% for book in genre.books.all %}
              <li>{{ book }}</li>
            {% endfor %}
          </ul>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <h3>No genres yet</h3>
  {% endif %}

  {% include 'common/footer-common.html' %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}
  	Base title
  {% endblock %}</title>
</head>
<body>
{% block body %}
	Base body
{% endblock %}
</body>
</html>

templates/common/footer-common.html
<div>
  <a href="{% url 'index' %}">Back to index</a>
</div>

templates/index.html
{% extends 'base.html' %}

{% block title %}
  Library Homepage
{% endblock %}

{% block body %}
  <h1>Welcome to our librery!</h1>
  <ul>
    <li><a href="{% url 'library:list' %}"
    >Book list</a></li>
    <li><a href="{% url 'library:genres-with-books' %}"
    >Genres</a></li>
  </ul>
{% endblock %}